### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by knil92** [sweetsoftware/Ares#14]
Hey,

I was wondering if you could help me with an error message im getting.  

C:\Users\Liam>L:\Ares-master\Ares-master\server\server.py
Traceback (most recent call last):
  File "L:\Ares-master\Ares-master\server\server.py", line 282, in <module>
    main()
  File "L:\Ares-master\Ares-master\server\server.py", line 269, in main
    cherrypy.config.update("conf/server.conf")
  File "C:\Python27\lib\cherrypy\_cpconfig.py", line 158, in update
    reprconf.Config.update(self, config)
  File "C:\Python27\lib\cherrypy\lib\reprconf.py", line 160, in update
    config = Parser().dict_from_file(config)
  File "C:\Python27\lib\cherrypy\lib\reprconf.py", line 232, in dict_from_file
    self.read(file)
  File "C:\Python27\lib\cherrypy\lib\reprconf.py", line 202, in read
    fp = open(filename)
IOError: [Errno 2] No such file or directory: 'conf/server.conf'

Thats the error message that pops up. I think it may have something to do with the cherrypy library but im not exactly experienced with python. I'm running windows 7 as well if that might be causing it not to work. I copied what it says in the cmd when i try running the server.py file. Before this it was saying something like error : no module named cherrypy, and i fixed that by putting cherrypy in my pythons library folder. So yeah any help you can give would be awesome.

Thanks,
Knil92

**Comment by knil92** [comment]
Okay so i got around this by opening command prompt in the folder that server.py was in. and then just doing the command server.py. I was originally opening up command prompt and typing the full file path to run the server.py but it doesnt like that for some reason. So I basically got around this by either just double clicking the server.py file, which ran the script in a python console window, or going to the folder that the server.py is located and shift + Right clicking and clicking open command prompt here and then typing the command server.py. I hope this helps any one else having similar issues. I also just want to say thank you as this is something that will help me once I'm done testing it. It will save me countless man hours having to connect to various servers and run scripts, do restarts, etc... This is just a handy little tool, and I hope that you develop this further and keep it python based :D
