### ISSUE TITLE
server error 

### ISSUE THREAD

**Issue by pretech86** [sweetsoftware/Ares#68]
when i try to start ./ares.py initdb it give methe following error

Traceback (most recent call last):
  File "./ares.py", line 19, in <module>
    from api import api
  File "/root/Downloads/2-undetectable payload generators/windows/Ares/server/api/__init__.py", line 16, in <module>
    import pygeoip
ImportError: No module named pygeoip

can you help me please

**Comment by pretech86** [comment]
i solved it thanks >>> pip install pygeoip >>> after that copy this module from its path to the server folder

**Comment by Puyodead1** [comment]
> i solved it thanks >>> pip install pygeoip >>> after that copy this module from its path to the server folder

If you solved it, close this issue.
