### ISSUE TITLE
pip install -r requirements.txt error

### ISSUE THREAD

**Issue by awlsdravg** [sweetsoftware/Ares#82]
logs error 

─(kali㉿kali)-[~/Ares]
└─$ pip install -r requirements.txt
Collecting altgraph==0.14
  Using cached altgraph-0.14-py2.py3-none-any.whl (22 kB)
Collecting certifi==2017.11.5
  Using cached certifi-2017.11.5-py2.py3-none-any.whl (330 kB)
Requirement already satisfied: chardet==3.0.4 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (3.0.4)
Collecting click==6.7
  Using cached click-6.7-py2.py3-none-any.whl (71 kB)
Collecting EasyProcess==0.2.3
  Using cached EasyProcess-0.2.3.tar.gz (10 kB)
Collecting Flask==0.12.2
  Using cached Flask-0.12.2-py2.py3-none-any.whl (83 kB)
Collecting Flask-Script==2.0.6
  Using cached Flask-Script-2.0.6.tar.gz (43 kB)
Collecting Flask-SQLAlchemy==2.3.2
  Using cached Flask_SQLAlchemy-2.3.2-py2.py3-none-any.whl (16 kB)
Collecting future==0.16.0
  Using cached future-0.16.0.tar.gz (824 kB)
Collecting gunicorn==19.7.1
  Using cached gunicorn-19.7.1-py2.py3-none-any.whl (111 kB)
Collecting idna==2.6
  Using cached idna-2.6-py2.py3-none-any.whl (56 kB)
Collecting itsdangerous==0.24
  Using cached itsdangerous-0.24.tar.gz (46 kB)
Collecting Jinja2==2.10
  Using cached Jinja2-2.10-py2.py3-none-any.whl (126 kB)
Collecting macholib==1.8
  Using cached macholib-1.8-py2.py3-none-any.whl (39 kB)
Collecting MarkupSafe==1.0
  Using cached MarkupSafe-1.0.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zh4u8v6g/MarkupSafe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zh4u8v6g/MarkupSafe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-l4_uyp61                                  
         cwd: /tmp/pip-install-zh4u8v6g/MarkupSafe/                        
    Complete output (5 lines):                                             
    Traceback (most recent call last):                                     
      File "<string>", line 1, in <module>                                 
      File "/tmp/pip-install-zh4u8v6g/MarkupSafe/setup.py", line 6, in <module>                                                                       
        from setuptools import setup, Extension, Feature                   
    ImportError: cannot import name 'Feature' from 'setuptools' (/usr/lib/python3/dist-packages/setuptools/__init__.py)                               
    ----------------------------------------                               
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by awlsdravg** [comment]
use Kali Linux 64-Bit (Live)
